---
- name: Check Terraform Version
  shell: "terraform --version | head -n1 | grep {{ terraform_install_version }}"
  failed_when: False
  changed_when: False
  register: current_terraform_version

- name: Download Terraform
  get_url:
    url: "{{ terraform_releases_url }}"
    dest: "{{ terraform_download_destination }}"
  when: current_terraform_version.rc != 0

- name: Create Terraform unzip dir
  file:
    path: "{{ terraform_unarchive_destination }}"
    state: directory
    mode: 0755
  when: current_terraform_version.rc != 0

- name: Unzip Terraform
  unarchive:
    src: "{{ terraform_download_destination }}"
    dest: "{{ terraform_unarchive_destination }}"
    copy: no
  when: current_terraform_version.rc != 0

- name: Move Terraform for execution
  copy:
    src: "{{ terraform_unarchive_destination }}/terraform"
    dest: "{{ terraform_execution_path }}"
    mode: u+x,g+x,o+x
    remote_src: true
  when: current_terraform_version.rc != 0